export const INSTRUCTOR_SIGNUP_LOADING = "STUDENT_SIGNUP_LOADING";
export const INSTRUCTOR_SIGNUP_SUCCESS = "STUDENT_SIGNUP_SUCCESS";
export const INSTRUCTOR_SIGNUP_ERROR = "STUDENT_SIGNUP_ERROR";


// Login Constants

export const INSTRUCTOR_LOGIN_LOADING = "STUDENT_LOGIN_LOADING";
export const INSTRUCTOR_LOGIN_SUCCESS = "STUDENT_LOGIN_SUCCESS";
export const INSTRUCTOR_LOGIN_ERROR = "STUDENT_LOGIN_ERROR";
