export const STUDENT_SIGNUP_LOADING = "STUDENT_SIGNUP_LOADING";
export const STUDENT_SIGNUP_SUCCESS = "STUDENT_SIGNUP_SUCCESS";
export const STUDENT_SIGNUP_ERROR = "STUDENT_SIGNUP_ERROR";


// Login Constants

export const STUDENT_LOGIN_LOADING = "STUDENT_LOGIN_LOADING";
export const STUDENT_LOGIN_SUCCESS = "STUDENT_LOGIN_SUCCESS";
export const STUDENT_LOGIN_ERROR = "STUDENT_LOGIN_ERROR";
